# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Bolt_config = debug
  Platform_config = debug
endif
ifeq ($(config),release)
  Bolt_config = release
  Platform_config = release
endif

PROJECTS := Bolt Platform

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Bolt:
ifneq (,$(Bolt_config))
	@echo "==== Building Bolt ($(Bolt_config)) ===="
	@${MAKE} --no-print-directory -C Bolt -f Makefile config=$(Bolt_config)
endif

Platform: Bolt
ifneq (,$(Platform_config))
	@echo "==== Building Platform ($(Platform_config)) ===="
	@${MAKE} --no-print-directory -C Platform -f Makefile config=$(Platform_config)
endif

clean:
	@${MAKE} --no-print-directory -C Bolt -f Makefile clean
	@${MAKE} --no-print-directory -C Platform -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Bolt"
	@echo "   Platform"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"