#pragma once

#include "../../dependencies/glfw/include/GLFW/glfw3.h"

#include "Utils.hpp"

#define BOLT_KEY_TYPE constexpr u16

namespace Bolt::keyglfw {

BOLT_KEY_TYPE KEY_KEY0 = GLFW_KEY_0;
BOLT_KEY_TYPE KEY_KEY1 = GLFW_KEY_1;
BOLT_KEY_TYPE KEY_KEY2 = GLFW_KEY_2;
BOLT_KEY_TYPE KEY_KEY3 = GLFW_KEY_3;
BOLT_KEY_TYPE KEY_KEY4 = GLFW_KEY_4;
BOLT_KEY_TYPE KEY_KEY5 = GLFW_KEY_5;
BOLT_KEY_TYPE KEY_KEY6 = GLFW_KEY_6;
BOLT_KEY_TYPE KEY_KEY7 = GLFW_KEY_7;
BOLT_KEY_TYPE KEY_KEY8 = GLFW_KEY_8;
BOLT_KEY_TYPE KEY_KEY9 = GLFW_KEY_9;
BOLT_KEY_TYPE KEY_EQUAL = GLFW_KEY_EQUAL;
BOLT_KEY_TYPE KEY_MINUS = GLFW_KEY_MINUS;

BOLT_KEY_TYPE KEY_SPACE = GLFW_KEY_SPACE;
BOLT_KEY_TYPE KEY_COMMA = GLFW_KEY_COMMA;
BOLT_KEY_TYPE KEY_PERIOD = GLFW_KEY_PERIOD;
BOLT_KEY_TYPE KEY_SEMICOLON = GLFW_KEY_SEMICOLON;
BOLT_KEY_TYPE KEY_APOSTROPHE = GLFW_KEY_APOSTROPHE;
BOLT_KEY_TYPE KEY_SLASH = GLFW_KEY_SLASH;

BOLT_KEY_TYPE KEY_LEFT_BRACKET = GLFW_KEY_LEFT_BRACKET;
BOLT_KEY_TYPE KEY_BACKSLASH = GLFW_KEY_BACKSLASH;
BOLT_KEY_TYPE KEY_RIGHT_BRACKET = GLFW_KEY_RIGHT_BRACKET;
BOLT_KEY_TYPE KEY_GRAVE_ACCENT = GLFW_KEY_GRAVE_ACCENT;
BOLT_KEY_TYPE KEY_WORLD_1 = GLFW_KEY_WORLD_1;
BOLT_KEY_TYPE KEY_WORLD_2 = GLFW_KEY_WORLD_2;

BOLT_KEY_TYPE KEY_A = GLFW_KEY_A;
BOLT_KEY_TYPE KEY_B = GLFW_KEY_B;
BOLT_KEY_TYPE KEY_C = GLFW_KEY_C;
BOLT_KEY_TYPE KEY_D = GLFW_KEY_D;
BOLT_KEY_TYPE KEY_E = GLFW_KEY_E;
BOLT_KEY_TYPE KEY_F = GLFW_KEY_F;
BOLT_KEY_TYPE KEY_G = GLFW_KEY_G;
BOLT_KEY_TYPE KEY_H = GLFW_KEY_H;
BOLT_KEY_TYPE KEY_I = GLFW_KEY_I;
BOLT_KEY_TYPE KEY_J = GLFW_KEY_J;
BOLT_KEY_TYPE KEY_K = GLFW_KEY_K;
BOLT_KEY_TYPE KEY_L = GLFW_KEY_L;
BOLT_KEY_TYPE KEY_M = GLFW_KEY_M;
BOLT_KEY_TYPE KEY_N = GLFW_KEY_N;
BOLT_KEY_TYPE KEY_O = GLFW_KEY_O;
BOLT_KEY_TYPE KEY_P = GLFW_KEY_P;
BOLT_KEY_TYPE KEY_Q = GLFW_KEY_Q;
BOLT_KEY_TYPE KEY_R = GLFW_KEY_R;
BOLT_KEY_TYPE KEY_S = GLFW_KEY_S;
BOLT_KEY_TYPE KEY_T = GLFW_KEY_T;
BOLT_KEY_TYPE KEY_U = GLFW_KEY_U;
BOLT_KEY_TYPE KEY_V = GLFW_KEY_V;
BOLT_KEY_TYPE KEY_W = GLFW_KEY_W;
BOLT_KEY_TYPE KEY_X = GLFW_KEY_X;
BOLT_KEY_TYPE KEY_Y = GLFW_KEY_Y;
BOLT_KEY_TYPE KEY_Z = GLFW_KEY_Z;

BOLT_KEY_TYPE KEY_ESCAPE = GLFW_KEY_ESCAPE;
BOLT_KEY_TYPE KEY_ENTER = GLFW_KEY_ENTER;
BOLT_KEY_TYPE KEY_TAB = GLFW_KEY_TAB;
BOLT_KEY_TYPE KEY_BACKSPACE = GLFW_KEY_BACKSPACE;
BOLT_KEY_TYPE KEY_INSERT = GLFW_KEY_INSERT;
BOLT_KEY_TYPE KEY_DELETE = GLFW_KEY_DELETE;
BOLT_KEY_TYPE KEY_RIGHT = GLFW_KEY_RIGHT;
BOLT_KEY_TYPE KEY_LEFT = GLFW_KEY_LEFT;
BOLT_KEY_TYPE KEY_DOWN = GLFW_KEY_DOWN;
BOLT_KEY_TYPE KEY_UP = GLFW_KEY_UP;
BOLT_KEY_TYPE KEY_PAGE_UP = GLFW_KEY_PAGE_UP;
BOLT_KEY_TYPE KEY_PAGE_DOWN = GLFW_KEY_PAGE_DOWN;
BOLT_KEY_TYPE KEY_HOME = GLFW_KEY_HOME;
BOLT_KEY_TYPE KEY_END = GLFW_KEY_END;
BOLT_KEY_TYPE KEY_CAPS_LOCK = GLFW_KEY_CAPS_LOCK;
BOLT_KEY_TYPE KEY_SCROLL_LOCK = GLFW_KEY_SCROLL_LOCK;
BOLT_KEY_TYPE KEY_NUM_LOCK = GLFW_KEY_NUM_LOCK;
BOLT_KEY_TYPE KEY_PRINT_SCREEN = GLFW_KEY_PRINT_SCREEN;
BOLT_KEY_TYPE KEY_PAUSE = GLFW_KEY_PAUSE;
BOLT_KEY_TYPE KEY_F1 = GLFW_KEY_F1;
BOLT_KEY_TYPE KEY_F2 = GLFW_KEY_F2;
BOLT_KEY_TYPE KEY_F3 = GLFW_KEY_F3;
BOLT_KEY_TYPE KEY_F4 = GLFW_KEY_F4;
BOLT_KEY_TYPE KEY_F5 = GLFW_KEY_F5;
BOLT_KEY_TYPE KEY_F6 = GLFW_KEY_F6;
BOLT_KEY_TYPE KEY_F7 = GLFW_KEY_F7;
BOLT_KEY_TYPE KEY_F8 = GLFW_KEY_F8;
BOLT_KEY_TYPE KEY_F9 = GLFW_KEY_F9;
BOLT_KEY_TYPE KEY_F10 = GLFW_KEY_F10;
BOLT_KEY_TYPE KEY_F11 = GLFW_KEY_F11;
BOLT_KEY_TYPE KEY_F12 = GLFW_KEY_F12;
BOLT_KEY_TYPE KEY_F13 = GLFW_KEY_F13;
BOLT_KEY_TYPE KEY_F14 = GLFW_KEY_F14;
BOLT_KEY_TYPE KEY_F15 = GLFW_KEY_F15;
BOLT_KEY_TYPE KEY_F16 = GLFW_KEY_F16;
BOLT_KEY_TYPE KEY_F17 = GLFW_KEY_F17;
BOLT_KEY_TYPE KEY_F18 = GLFW_KEY_F18;
BOLT_KEY_TYPE KEY_F19 = GLFW_KEY_F19;
BOLT_KEY_TYPE KEY_F20 = GLFW_KEY_F20;
BOLT_KEY_TYPE KEY_F21 = GLFW_KEY_F21;
BOLT_KEY_TYPE KEY_F22 = GLFW_KEY_F22;
BOLT_KEY_TYPE KEY_F23 = GLFW_KEY_F23;
BOLT_KEY_TYPE KEY_F24 = GLFW_KEY_F24;
BOLT_KEY_TYPE KEY_F25 = GLFW_KEY_F25;
BOLT_KEY_TYPE KEY_KP_0 = GLFW_KEY_KP_0;
BOLT_KEY_TYPE KEY_KP_1 = GLFW_KEY_KP_1;
BOLT_KEY_TYPE KEY_KP_2 = GLFW_KEY_KP_2;
BOLT_KEY_TYPE KEY_KP_3 = GLFW_KEY_KP_3;
BOLT_KEY_TYPE KEY_KP_4 = GLFW_KEY_KP_4;
BOLT_KEY_TYPE KEY_KP_5 = GLFW_KEY_KP_5;
BOLT_KEY_TYPE KEY_KP_6 = GLFW_KEY_KP_6;
BOLT_KEY_TYPE KEY_KP_7 = GLFW_KEY_KP_7;
BOLT_KEY_TYPE KEY_KP_8 = GLFW_KEY_KP_8;
BOLT_KEY_TYPE KEY_KP_9 = GLFW_KEY_KP_9;
BOLT_KEY_TYPE KEY_KP_DECIMAL = GLFW_KEY_KP_DECIMAL;
BOLT_KEY_TYPE KEY_KP_DIVIDE = GLFW_KEY_KP_DIVIDE;
BOLT_KEY_TYPE KEY_KP_MULTIPLY = GLFW_KEY_KP_MULTIPLY;
BOLT_KEY_TYPE KEY_KP_SUBTRACT = GLFW_KEY_KP_SUBTRACT;
BOLT_KEY_TYPE KEY_KP_ADD = GLFW_KEY_KP_ADD;
BOLT_KEY_TYPE KEY_KP_ENTER = GLFW_KEY_KP_ENTER;
BOLT_KEY_TYPE KEY_KP_EQUAL = GLFW_KEY_KP_EQUAL;
BOLT_KEY_TYPE KEY_LEFT_SHIFT = GLFW_KEY_LEFT_SHIFT;
BOLT_KEY_TYPE KEY_LEFT_CONTROL = GLFW_KEY_LEFT_CONTROL;
BOLT_KEY_TYPE KEY_LEFT_ALT = GLFW_KEY_LEFT_ALT;
BOLT_KEY_TYPE KEY_LEFT_SUPER = GLFW_KEY_LEFT_SUPER;
BOLT_KEY_TYPE KEY_RIGHT_SHIFT = GLFW_KEY_RIGHT_SHIFT;
BOLT_KEY_TYPE KEY_RIGHT_CONTROL = GLFW_KEY_RIGHT_CONTROL;
BOLT_KEY_TYPE KEY_RIGHT_ALT = GLFW_KEY_RIGHT_ALT;
BOLT_KEY_TYPE KEY_RIGHT_SUPER = GLFW_KEY_RIGHT_SUPER;
BOLT_KEY_TYPE KEY_MENU = GLFW_KEY_MENU;

BOLT_KEY_TYPE KEY_LAST = GLFW_KEY_MENU;

} // namespace Bolt::keyglfw
